// flow-typed signature: 0309d21a1e7b29a5c1e2b280418418d7
// flow-typed version: <<STUB>>/react-native-svg-charts_v^5.2.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg-charts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg-charts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg-charts/src/animated-path' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/area-chart' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/bar-chart/bar-chart-grouped' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/bar-chart/bar-chart' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/bar-chart/index' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/card' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/chart-decorators/horizontal-line' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/chart-decorators/index' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/chart-decorators/point' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/chart-decorators/tooltip' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/chart' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/decorator' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/extra' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/grid' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/index' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/line-chart' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/pie-chart' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/progress-circle' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/stacked-area-chart' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/stacked-bar-chart' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/util' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/x-axis' {
  declare module.exports: any;
}

declare module 'react-native-svg-charts/src/y-axis' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg-charts/index' {
  declare module.exports: $Exports<'react-native-svg-charts'>;
}
declare module 'react-native-svg-charts/index.js' {
  declare module.exports: $Exports<'react-native-svg-charts'>;
}
declare module 'react-native-svg-charts/src/animated-path.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/animated-path'>;
}
declare module 'react-native-svg-charts/src/area-chart.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/area-chart'>;
}
declare module 'react-native-svg-charts/src/bar-chart/bar-chart-grouped.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/bar-chart/bar-chart-grouped'>;
}
declare module 'react-native-svg-charts/src/bar-chart/bar-chart.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/bar-chart/bar-chart'>;
}
declare module 'react-native-svg-charts/src/bar-chart/index.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/bar-chart/index'>;
}
declare module 'react-native-svg-charts/src/card.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/card'>;
}
declare module 'react-native-svg-charts/src/chart-decorators/horizontal-line.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/chart-decorators/horizontal-line'>;
}
declare module 'react-native-svg-charts/src/chart-decorators/index.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/chart-decorators/index'>;
}
declare module 'react-native-svg-charts/src/chart-decorators/point.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/chart-decorators/point'>;
}
declare module 'react-native-svg-charts/src/chart-decorators/tooltip.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/chart-decorators/tooltip'>;
}
declare module 'react-native-svg-charts/src/chart.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/chart'>;
}
declare module 'react-native-svg-charts/src/decorator.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/decorator'>;
}
declare module 'react-native-svg-charts/src/extra.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/extra'>;
}
declare module 'react-native-svg-charts/src/grid.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/grid'>;
}
declare module 'react-native-svg-charts/src/index.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/index'>;
}
declare module 'react-native-svg-charts/src/line-chart.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/line-chart'>;
}
declare module 'react-native-svg-charts/src/pie-chart.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/pie-chart'>;
}
declare module 'react-native-svg-charts/src/progress-circle.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/progress-circle'>;
}
declare module 'react-native-svg-charts/src/stacked-area-chart.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/stacked-area-chart'>;
}
declare module 'react-native-svg-charts/src/stacked-bar-chart.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/stacked-bar-chart'>;
}
declare module 'react-native-svg-charts/src/util.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/util'>;
}
declare module 'react-native-svg-charts/src/x-axis.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/x-axis'>;
}
declare module 'react-native-svg-charts/src/y-axis.js' {
  declare module.exports: $Exports<'react-native-svg-charts/src/y-axis'>;
}
