// flow-typed signature: d3716d9d3d486ccee1abbe340037a5cc
// flow-typed version: <<STUB>>/redux-orm_v0.12.2/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-orm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-orm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-orm/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'redux-orm/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-orm/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-orm/dist/redux-orm' {
  declare module.exports: any;
}

declare module 'redux-orm/dist/redux-orm.min' {
  declare module.exports: any;
}

declare module 'redux-orm/es/constants' {
  declare module.exports: any;
}

declare module 'redux-orm/es/db/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/es/db/index' {
  declare module.exports: any;
}

declare module 'redux-orm/es/db/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/es/descriptors' {
  declare module.exports: any;
}

declare module 'redux-orm/es/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/es/index' {
  declare module.exports: any;
}

declare module 'redux-orm/es/memoize' {
  declare module.exports: any;
}

declare module 'redux-orm/es/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/es/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/es/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/es/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/es/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/es5Test' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/functional/concurrentSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/functional/deprecations' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/functional/es5' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/functional/immutableSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/functional/many2many' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/functional/mutableSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/functional/performance' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/helpers' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/integration/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testDatabase' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testDeprecations' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testIntegrations' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testModel' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testORM' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testPerformance' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testQuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testReduxIntegration' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testSession' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testTable' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/testUtils' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/unit/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/es/test/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/es/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/gulpfile' {
  declare module.exports: any;
}

declare module 'redux-orm/jest.config' {
  declare module.exports: any;
}

declare module 'redux-orm/jest.es5.config' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/db/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/db/index' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/db/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/descriptors' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/index' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/memoize' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/functional/concurrentSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/functional/deprecations' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/functional/es5' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/functional/immutableSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/functional/many2many' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/functional/mutableSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/functional/performance' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/helpers' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/integration/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/unit/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/src/constants' {
  declare module.exports: any;
}

declare module 'redux-orm/src/db/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/src/db/index' {
  declare module.exports: any;
}

declare module 'redux-orm/src/db/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/src/descriptors' {
  declare module.exports: any;
}

declare module 'redux-orm/src/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/src/index' {
  declare module.exports: any;
}

declare module 'redux-orm/src/memoize' {
  declare module.exports: any;
}

declare module 'redux-orm/src/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/src/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/src/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/src/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/src/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/functional/concurrentSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/functional/deprecations' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/functional/es5' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/functional/immutableSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/functional/many2many' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/functional/mutableSessions' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/functional/performance' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/helpers' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/integration/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/unit/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/src/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/webpack.common' {
  declare module.exports: any;
}

declare module 'redux-orm/webpack.dev' {
  declare module.exports: any;
}

declare module 'redux-orm/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-orm/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'redux-orm/coverage/lcov-report/block-navigation'>;
}
declare module 'redux-orm/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-orm/coverage/lcov-report/prettify'>;
}
declare module 'redux-orm/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-orm/coverage/lcov-report/sorter'>;
}
declare module 'redux-orm/dist/redux-orm.js' {
  declare module.exports: $Exports<'redux-orm/dist/redux-orm'>;
}
declare module 'redux-orm/dist/redux-orm.min.js' {
  declare module.exports: $Exports<'redux-orm/dist/redux-orm.min'>;
}
declare module 'redux-orm/es/constants.js' {
  declare module.exports: $Exports<'redux-orm/es/constants'>;
}
declare module 'redux-orm/es/db/Database.js' {
  declare module.exports: $Exports<'redux-orm/es/db/Database'>;
}
declare module 'redux-orm/es/db/index.js' {
  declare module.exports: $Exports<'redux-orm/es/db/index'>;
}
declare module 'redux-orm/es/db/Table.js' {
  declare module.exports: $Exports<'redux-orm/es/db/Table'>;
}
declare module 'redux-orm/es/descriptors.js' {
  declare module.exports: $Exports<'redux-orm/es/descriptors'>;
}
declare module 'redux-orm/es/fields.js' {
  declare module.exports: $Exports<'redux-orm/es/fields'>;
}
declare module 'redux-orm/es/index.js' {
  declare module.exports: $Exports<'redux-orm/es/index'>;
}
declare module 'redux-orm/es/memoize.js' {
  declare module.exports: $Exports<'redux-orm/es/memoize'>;
}
declare module 'redux-orm/es/Model.js' {
  declare module.exports: $Exports<'redux-orm/es/Model'>;
}
declare module 'redux-orm/es/ORM.js' {
  declare module.exports: $Exports<'redux-orm/es/ORM'>;
}
declare module 'redux-orm/es/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/es/QuerySet'>;
}
declare module 'redux-orm/es/redux.js' {
  declare module.exports: $Exports<'redux-orm/es/redux'>;
}
declare module 'redux-orm/es/Session.js' {
  declare module.exports: $Exports<'redux-orm/es/Session'>;
}
declare module 'redux-orm/es/test/es5Test.js' {
  declare module.exports: $Exports<'redux-orm/es/test/es5Test'>;
}
declare module 'redux-orm/es/test/functional/concurrentSessions.js' {
  declare module.exports: $Exports<'redux-orm/es/test/functional/concurrentSessions'>;
}
declare module 'redux-orm/es/test/functional/deprecations.js' {
  declare module.exports: $Exports<'redux-orm/es/test/functional/deprecations'>;
}
declare module 'redux-orm/es/test/functional/es5.js' {
  declare module.exports: $Exports<'redux-orm/es/test/functional/es5'>;
}
declare module 'redux-orm/es/test/functional/immutableSessions.js' {
  declare module.exports: $Exports<'redux-orm/es/test/functional/immutableSessions'>;
}
declare module 'redux-orm/es/test/functional/many2many.js' {
  declare module.exports: $Exports<'redux-orm/es/test/functional/many2many'>;
}
declare module 'redux-orm/es/test/functional/mutableSessions.js' {
  declare module.exports: $Exports<'redux-orm/es/test/functional/mutableSessions'>;
}
declare module 'redux-orm/es/test/functional/performance.js' {
  declare module.exports: $Exports<'redux-orm/es/test/functional/performance'>;
}
declare module 'redux-orm/es/test/helpers.js' {
  declare module.exports: $Exports<'redux-orm/es/test/helpers'>;
}
declare module 'redux-orm/es/test/integration/redux.js' {
  declare module.exports: $Exports<'redux-orm/es/test/integration/redux'>;
}
declare module 'redux-orm/es/test/testDatabase.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testDatabase'>;
}
declare module 'redux-orm/es/test/testDeprecations.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testDeprecations'>;
}
declare module 'redux-orm/es/test/testIntegrations.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testIntegrations'>;
}
declare module 'redux-orm/es/test/testModel.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testModel'>;
}
declare module 'redux-orm/es/test/testORM.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testORM'>;
}
declare module 'redux-orm/es/test/testPerformance.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testPerformance'>;
}
declare module 'redux-orm/es/test/testQuerySet.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testQuerySet'>;
}
declare module 'redux-orm/es/test/testReduxIntegration.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testReduxIntegration'>;
}
declare module 'redux-orm/es/test/testSession.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testSession'>;
}
declare module 'redux-orm/es/test/testTable.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testTable'>;
}
declare module 'redux-orm/es/test/testUtils.js' {
  declare module.exports: $Exports<'redux-orm/es/test/testUtils'>;
}
declare module 'redux-orm/es/test/unit/Database.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/Database'>;
}
declare module 'redux-orm/es/test/unit/fields.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/fields'>;
}
declare module 'redux-orm/es/test/unit/Model.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/Model'>;
}
declare module 'redux-orm/es/test/unit/ORM.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/ORM'>;
}
declare module 'redux-orm/es/test/unit/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/QuerySet'>;
}
declare module 'redux-orm/es/test/unit/Session.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/Session'>;
}
declare module 'redux-orm/es/test/unit/Table.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/Table'>;
}
declare module 'redux-orm/es/test/unit/utils.js' {
  declare module.exports: $Exports<'redux-orm/es/test/unit/utils'>;
}
declare module 'redux-orm/es/test/utils.js' {
  declare module.exports: $Exports<'redux-orm/es/test/utils'>;
}
declare module 'redux-orm/es/utils.js' {
  declare module.exports: $Exports<'redux-orm/es/utils'>;
}
declare module 'redux-orm/gulpfile.js' {
  declare module.exports: $Exports<'redux-orm/gulpfile'>;
}
declare module 'redux-orm/jest.config.js' {
  declare module.exports: $Exports<'redux-orm/jest.config'>;
}
declare module 'redux-orm/jest.es5.config.js' {
  declare module.exports: $Exports<'redux-orm/jest.es5.config'>;
}
declare module 'redux-orm/lib/constants.js' {
  declare module.exports: $Exports<'redux-orm/lib/constants'>;
}
declare module 'redux-orm/lib/db/Database.js' {
  declare module.exports: $Exports<'redux-orm/lib/db/Database'>;
}
declare module 'redux-orm/lib/db/index.js' {
  declare module.exports: $Exports<'redux-orm/lib/db/index'>;
}
declare module 'redux-orm/lib/db/Table.js' {
  declare module.exports: $Exports<'redux-orm/lib/db/Table'>;
}
declare module 'redux-orm/lib/descriptors.js' {
  declare module.exports: $Exports<'redux-orm/lib/descriptors'>;
}
declare module 'redux-orm/lib/fields.js' {
  declare module.exports: $Exports<'redux-orm/lib/fields'>;
}
declare module 'redux-orm/lib/index.js' {
  declare module.exports: $Exports<'redux-orm/lib/index'>;
}
declare module 'redux-orm/lib/memoize.js' {
  declare module.exports: $Exports<'redux-orm/lib/memoize'>;
}
declare module 'redux-orm/lib/Model.js' {
  declare module.exports: $Exports<'redux-orm/lib/Model'>;
}
declare module 'redux-orm/lib/ORM.js' {
  declare module.exports: $Exports<'redux-orm/lib/ORM'>;
}
declare module 'redux-orm/lib/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/lib/QuerySet'>;
}
declare module 'redux-orm/lib/redux.js' {
  declare module.exports: $Exports<'redux-orm/lib/redux'>;
}
declare module 'redux-orm/lib/Session.js' {
  declare module.exports: $Exports<'redux-orm/lib/Session'>;
}
declare module 'redux-orm/lib/test/functional/concurrentSessions.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/functional/concurrentSessions'>;
}
declare module 'redux-orm/lib/test/functional/deprecations.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/functional/deprecations'>;
}
declare module 'redux-orm/lib/test/functional/es5.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/functional/es5'>;
}
declare module 'redux-orm/lib/test/functional/immutableSessions.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/functional/immutableSessions'>;
}
declare module 'redux-orm/lib/test/functional/many2many.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/functional/many2many'>;
}
declare module 'redux-orm/lib/test/functional/mutableSessions.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/functional/mutableSessions'>;
}
declare module 'redux-orm/lib/test/functional/performance.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/functional/performance'>;
}
declare module 'redux-orm/lib/test/helpers.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/helpers'>;
}
declare module 'redux-orm/lib/test/integration/redux.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/integration/redux'>;
}
declare module 'redux-orm/lib/test/unit/Database.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/Database'>;
}
declare module 'redux-orm/lib/test/unit/fields.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/fields'>;
}
declare module 'redux-orm/lib/test/unit/Model.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/Model'>;
}
declare module 'redux-orm/lib/test/unit/ORM.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/ORM'>;
}
declare module 'redux-orm/lib/test/unit/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/QuerySet'>;
}
declare module 'redux-orm/lib/test/unit/Session.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/Session'>;
}
declare module 'redux-orm/lib/test/unit/Table.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/Table'>;
}
declare module 'redux-orm/lib/test/unit/utils.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/unit/utils'>;
}
declare module 'redux-orm/lib/utils.js' {
  declare module.exports: $Exports<'redux-orm/lib/utils'>;
}
declare module 'redux-orm/src/constants.js' {
  declare module.exports: $Exports<'redux-orm/src/constants'>;
}
declare module 'redux-orm/src/db/Database.js' {
  declare module.exports: $Exports<'redux-orm/src/db/Database'>;
}
declare module 'redux-orm/src/db/index.js' {
  declare module.exports: $Exports<'redux-orm/src/db/index'>;
}
declare module 'redux-orm/src/db/Table.js' {
  declare module.exports: $Exports<'redux-orm/src/db/Table'>;
}
declare module 'redux-orm/src/descriptors.js' {
  declare module.exports: $Exports<'redux-orm/src/descriptors'>;
}
declare module 'redux-orm/src/fields.js' {
  declare module.exports: $Exports<'redux-orm/src/fields'>;
}
declare module 'redux-orm/src/index.js' {
  declare module.exports: $Exports<'redux-orm/src/index'>;
}
declare module 'redux-orm/src/memoize.js' {
  declare module.exports: $Exports<'redux-orm/src/memoize'>;
}
declare module 'redux-orm/src/Model.js' {
  declare module.exports: $Exports<'redux-orm/src/Model'>;
}
declare module 'redux-orm/src/ORM.js' {
  declare module.exports: $Exports<'redux-orm/src/ORM'>;
}
declare module 'redux-orm/src/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/src/QuerySet'>;
}
declare module 'redux-orm/src/redux.js' {
  declare module.exports: $Exports<'redux-orm/src/redux'>;
}
declare module 'redux-orm/src/Session.js' {
  declare module.exports: $Exports<'redux-orm/src/Session'>;
}
declare module 'redux-orm/src/test/functional/concurrentSessions.js' {
  declare module.exports: $Exports<'redux-orm/src/test/functional/concurrentSessions'>;
}
declare module 'redux-orm/src/test/functional/deprecations.js' {
  declare module.exports: $Exports<'redux-orm/src/test/functional/deprecations'>;
}
declare module 'redux-orm/src/test/functional/es5.js' {
  declare module.exports: $Exports<'redux-orm/src/test/functional/es5'>;
}
declare module 'redux-orm/src/test/functional/immutableSessions.js' {
  declare module.exports: $Exports<'redux-orm/src/test/functional/immutableSessions'>;
}
declare module 'redux-orm/src/test/functional/many2many.js' {
  declare module.exports: $Exports<'redux-orm/src/test/functional/many2many'>;
}
declare module 'redux-orm/src/test/functional/mutableSessions.js' {
  declare module.exports: $Exports<'redux-orm/src/test/functional/mutableSessions'>;
}
declare module 'redux-orm/src/test/functional/performance.js' {
  declare module.exports: $Exports<'redux-orm/src/test/functional/performance'>;
}
declare module 'redux-orm/src/test/helpers.js' {
  declare module.exports: $Exports<'redux-orm/src/test/helpers'>;
}
declare module 'redux-orm/src/test/integration/redux.js' {
  declare module.exports: $Exports<'redux-orm/src/test/integration/redux'>;
}
declare module 'redux-orm/src/test/unit/Database.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/Database'>;
}
declare module 'redux-orm/src/test/unit/fields.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/fields'>;
}
declare module 'redux-orm/src/test/unit/Model.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/Model'>;
}
declare module 'redux-orm/src/test/unit/ORM.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/ORM'>;
}
declare module 'redux-orm/src/test/unit/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/QuerySet'>;
}
declare module 'redux-orm/src/test/unit/Session.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/Session'>;
}
declare module 'redux-orm/src/test/unit/Table.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/Table'>;
}
declare module 'redux-orm/src/test/unit/utils.js' {
  declare module.exports: $Exports<'redux-orm/src/test/unit/utils'>;
}
declare module 'redux-orm/src/utils.js' {
  declare module.exports: $Exports<'redux-orm/src/utils'>;
}
declare module 'redux-orm/webpack.common.js' {
  declare module.exports: $Exports<'redux-orm/webpack.common'>;
}
declare module 'redux-orm/webpack.dev.js' {
  declare module.exports: $Exports<'redux-orm/webpack.dev'>;
}
declare module 'redux-orm/webpack.prod.js' {
  declare module.exports: $Exports<'redux-orm/webpack.prod'>;
}
