// flow-typed signature: faf29ab6566bbe2784b18e2a12182d17
// flow-typed version: <<STUB>>/redux-persist/lib/storage_v1.13.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist/lib/storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist/lib/storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist/lib/storage/createWebStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/getStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/index.native' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/session' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist/lib/storage/createWebStorage.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/createWebStorage'>;
}
declare module 'redux-persist/lib/storage/getStorage.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/getStorage'>;
}
declare module 'redux-persist/lib/storage/index' {
  declare module.exports: $Exports<'redux-persist/lib/storage'>;
}
declare module 'redux-persist/lib/storage/index.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage'>;
}
declare module 'redux-persist/lib/storage/index.native.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/index.native'>;
}
declare module 'redux-persist/lib/storage/session.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/session'>;
}
